[
    uuid(D15C6042-5770-4007-8608-EBF3A1ED8083),
    version(1.0)
]
library WzLib
{
    importlib("stdole2.tlb");
    import "IWzGr2DLayer.idl";

    [
        object,
        uuid(E576EA33-D465-4F08-AAB1-E78DF73EE6D9)
    ]
    interface IWzGr2D : IUnknown {
        HRESULT Initialize([in] UINT uWidth, [in] UINT uHeight, [in, optional] VARIANT vHwnd, [in, optional] VARIANT vBPP, [in, optional] VARIANT vRefreshRate);
        HRESULT Uninitialize();
        [propget] HRESULT nextRenderTime([out, retval] INT* pnTime);
        HRESULT UpdateCurrentTime([in] INT tTime);
        HRESULT RenderFrame([in] INT tCur);
        HRESULT SetFrameSkip();
        HRESULT ToggleFpsPanel();
        [propget] HRESULT width([out, retval] UINT* puWidth);
        [propget] HRESULT height([out, retval] UINT* puHeight);
        HRESULT screenResolution([in] UINT uWidth, [in] UINT uHeight, [in] UINT);
        [propget] HRESULT bpp([out, retval] UINT* puBPP);
        [propget] HRESULT refreshRate([out, retval] UINT* puRefreshRate);
        [propget] HRESULT fps100([out, retval] UINT* puFps100);
        [propget] HRESULT currentTime([out, retval] INT* pnCurrentTime);
        [propget] HRESULT fullScreen([out, retval] INT* pnFullScreen);
        [propput] HRESULT fullScreen([in] INT nFullScreen);
        [propget] HRESULT backColor([out, retval] UINT* puColor);
        [propput] HRESULT backColor([in] UINT uColor);
        [propget] HRESULT redTone([out, retval] IWzVector2D** ppVector);
        [propget] HRESULT greenBlueTone([out, retval] IWzVector2D** ppVector);
        [propget] HRESULT center([out, retval] IWzVector2D** ppVector);
        HRESULT GetSnapshot([in] VARIANT pvBuffer, [in] UINT uBufferSize, [in] INT x, [in] INT y);
        HRESULT GetSnapshotFullScreen([in] VARIANT pvBuffer, [in] UINT uBufferSize);
        HRESULT GetDeviceMaxScreen([out] UINT* puWidth, [out] UINT* puHeight);
        HRESULT CreateLayer([in] INT nLeft, [in] INT nTop, [in] UINT uWidth, [in] UINT uHeight, [in] INT nZ, [in, optional] VARIANT vCanvas, [in, optional] VARIANT dwFilter, [in, optional] VARIANT vPostRender, [out, retval] IWzGr2DLayer** ppLayer);
        HRESULT AdjustCenter([in] INT nAdjustCenterX, [in] INT nAdjustCenterY);
        HRESULT TakeScreenShot([in] BSTR sFileName, [in] INT nFileFormat);
        HRESULT SetCameraReverseTime([in] UINT tDuration);
        HRESULT SetScreenScale([in] INT nResult);
        HRESULT GetScreenScale([out] INT* pnResult);
        HRESULT SetShader([in] UINT nType);
        HRESULT UnSetShader([in] UINT nType);
        HRESULT SetVideoMode([in] INT bMode);
        HRESULT SetVideoPath([in] BSTR sPath, [in] INT unk1, [in] INT unk2);
        HRESULT PlayVideo();
        HRESULT PauseVideo([in] INT nPause);
        HRESULT StopVideo();
        [propget] HRESULT videoStatus([out, retval] INT* pnStatus);
        [propput] HRESULT videoVolume([in] INT nVolume);
        HRESULT EnabledShader([in] INT bIncludeOff, [out, retval] INT* pnResult);
        HRESULT GetHardwareMaxTexture([out] UINT* pnMaxWidth, [out] UINT* pnMaxHeight);
        HRESULT GetQViewPoint([in] POINT, [in] POINT, [in] FLOAT, [in] FLOAT, [out, retval] POINT*);
        HRESULT GetQViewPointInv([in] POINT, [in] POINT, [in] FLOAT, [in] FLOAT, [out, retval] POINT*);
        HRESULT CheckMode([in] UINT, [in] UINT, [in] UINT);
        HRESULT InitializeAfcTv([out] INT*, [out] INT*);
        HRESULT AfcTvLogin([in] BSTR, [in] BSTR, [out] INT*, [out] INT*, [out] INT*);
        HRESULT AfcTvLogout();
        HRESULT AfcTvSetup([in] BSTR, [in] BSTR, [in] INT, [in] INT, [in] INT, [out, retval] INT*);
        HRESULT AfcTvStart([in] INT, [in] BSTR, [in] BSTR, [in] INT, [in] INT, [in] INT, [out, retval] INT*);
        HRESULT AfcTvStop();
        HRESULT AfcTvPause([in] INT, [out, retval] INT*);
        HRESULT AfcTvChatMessage([in] BSTR, [out, retval] INT*);
        HRESULT GetAfcTvState([out, retval] INT*);
        HRESULT IsAfcTvPause([out, retval] INT*);
        HRESULT SetBlur([in] INT, [in] INT, [in] INT, [in] INT, [in] INT, [in] INT);
        HRESULT GetAvailableTextureMem([out, retval] UINT*);
        HRESULT GetDxDevice([out, retval] UINT**);
        HRESULT GetLayerList([out, retval] UINT**);
        HRESULT SetCameraRotate([in] FLOAT);
        HRESULT GetCameraRotate([out, retval] FLOAT*);
        HRESULT SetBlurMaskCanvas([in] IWzCanvas*);
        HRESULT IsPow2Texture([out, retval] INT*);
        HRESULT renderToTexture([out, retval] IWzCanvas**);
        HRESULT forceFilter([in] INT);
        HRESULT InitBlackBoxCallBack([out, retval] INT*);
    };
};