[
    uuid(D15C6042-5770-4007-8608-EBF3A1ED8083),
    version(1.0)
]
library WzLib
{
    importlib("stdole2.tlb");
    import "IWzNameSpace.idl";
    import "IWzSeekableArchive.idl";

    [
        object,
        uuid(E610818B-038D-4522-9232-30FCD5F4737C)
    ]
    interface IWzPackage : IWzNameSpace {
        HRESULT Init([in] BSTR sKey, [in] BSTR sBaseUOL, [in] IWzSeekableArchive pArchive);
    };
};