[
    uuid(D15C6042-5770-4007-8608-EBF3A1ED8083),
    version(1.0)
]
library WzLib
{
    importlib("stdole2.tlb");
    import "IWzArchive.idl";

    [
        object,
        uuid(35C1F133-7F61-496E-878F-9A1758AFA9EA)
    ]
    interface IWzSeekableArchive : IWzArchive {
        [propput] HRESULT position([in] UINT uPos);
        [propget] HRESULT length([out, retval] UINT* puLength);
        [propput] HRESULT length([in] UINT uLength);
        [propget] HRESULT address([out, retval] VARIANT* pv);
        HRESULT Rewind();
        HRESULT ReadLock([in] BSTR sRelUOL, [in] UINT uSize, [out, retval] IWzSeekableArchive** ppArchive);
    };
};