[
    uuid(D15C6042-5770-4007-8608-EBF3A1ED8083),
    version(1.0)
]
library WzLib
{
    importlib("stdole2.tlb");
    import "IWzShape2D.idl";

    typedef enum VECTOR2D_MOVE {
        VM_FOREVER = 0x10000000
    } VECTOR2D_MOVE;

    [
        object,
        uuid(F28BD1ED-3DEB-4F92-9EEC-10EF5A1C3FB4)
    ]
    interface IWzVector2D : IWzShape2D {
        [propget] HRESULT currentTime([out, retval] INT* pnTime);
        [propput] HRESULT currentTime([in] INT nTime);
        [propget] HRESULT origin([out, retval] VARIANT* pvOrigin);
        [propput] HRESULT origin([in] VARIANT vOrigin);
        [propget] HRESULT rx([out, retval] INT* pVal);
        [propput] HRESULT rx([in] INT newVal);
        [propget] HRESULT ry([out, retval] INT* pVal);
        [propput] HRESULT ry([in] INT newVal);
        [propget] HRESULT a([out, retval] DOUBLE* pVal);
        [propget] HRESULT ra([out, retval] DOUBLE* pVal);
        [propput] HRESULT ra([in] DOUBLE newVal);
        [propget] HRESULT flipX([out, retval] INT* pVal);
        [propput] HRESULT flipX([in] INT newVal);
        HRESULT _GetSnapshot([out] INT* px, [out] INT* py, [out] INT* prx, [out] INT* pry, [out] INT* pxOrg, [out] INT* pyOrg, [out] DOUBLE* pa, [out] DOUBLE* paOrg, [in, optional] VARIANT vTime);
        HRESULT RelMove([in] INT nX, [in] INT nY, [in, optional] VARIANT nTime, [in, optional] VARIANT nType);
        HRESULT RelOffset([in] INT nDX, [in] INT nDY, [in, optional] VARIANT nTime, [in, optional] VARIANT nType);
        HRESULT Ratio([in] IWzVector2D* pOrigin, [in] INT nOriginWidth, [in] INT nOriginHeight, [in] INT nScaleWidth, [in] INT nScaleHeight);
        HRESULT WrapClip([in] VARIANT pOrigin, [in] INT nWrapLeft, [in] INT nWrapTop, [in] UINT uWrapWidth, [in] UINT uWrapHeight, [in, optional] VARIANT bClip);
        HRESULT Rotate([in] DOUBLE dAngleAmount, [in, optional] VARIANT nTime);
        [propget] HRESULT looseLevel([out, retval] UINT* puLevel);
        [propput] HRESULT looseLevel([in] UINT uLevel);
        HRESULT Fly([in] VARIANT* aVar, [in] INT nArgs);
    };
};